### ISSUE TITLE
Cannot download some books in Readmoo

### ISSUE THREAD

**Issue by NomadThanatos** [msglight4874/epub-exporter#1]
This book cannot be downloaded.
https://readmoo.com/book/210095766000101

And it seems that all books in this series cannot be downloaded, I have tried multiple books, none of them success.
https://readmoo.com/installment/885

If you want some logs, you can add them and I could fetch the logs for you. As for now, I do not find any logs related to this and not really look into the code yet.

**Comment by david-zw-liu** [comment]
Hi @NomadThanatos ,

I figured out the problem is that regex expression in exporter cannot find root path.
And I fixed this problem in latest master branch already.
Could you reinstall the extension from latest master and try download the book from that series?
If there is any problem still, please let me know.

Thanks.

**Comment by NomadThanatos** [comment]
The fix solves this problem.
